// <auto-generated />
using DiakKurzusApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace WebApplication2.Migrations
{
    [DbContext(typeof(EgyetemContext))]
    [Migration("20260310083252_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.24");

            modelBuilder.Entity("WebApplication2.Models.Diak", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BeiratkozasEve")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NeptunKod")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nev")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Szak")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Diakok");
                });

            modelBuilder.Entity("WebApplication2.Models.Kurzus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FelelosTanszek")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Kredit")
                        .HasColumnType("INTEGER");

                    b.Property<string>("KurzusNev")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Oktato")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Kurzusok");
                });
#pragma warning restore 612, 618
        }
    }
}
