// <auto-generated />
using FilmLista.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FilmLista.Migrations
{
    [DbContext(typeof(FilmContext))]
    partial class FilmContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.25");

            modelBuilder.Entity("FilmLista.Models.Film", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cim")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("IMDBPontszam")
                        .HasColumnType("REAL");

                    b.Property<int>("MegjelenesiEv")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Mufaj")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Rendezo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Filmek");
                });
#pragma warning restore 612, 618
        }
    }
}
