// <auto-generated />
using System;
using Konyvkatalogus.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Konyvkatalogus.Migrations
{
    [DbContext(typeof(KonyvContext))]
    [Migration("20260423080232_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Konyvkatalogus.Models.Konyv", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Cim")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<string>("Isbn")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Kategoria")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("KiadasIdeje")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Szerzo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Konyv");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cim = "A Gyűrűk Ura: A Gyűrű Szövetsége",
                            Isbn = "978-0-618-00222-8",
                            Kategoria = "Fantasy",
                            KiadasIdeje = new DateTime(1954, 7, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Szerzo = "J.R.R. Tolkien"
                        },
                        new
                        {
                            Id = 2,
                            Cim = "Harry Potter és a Bölcsek Köve",
                            Isbn = "978-0-7475-3269-9",
                            Kategoria = "Fantasy",
                            KiadasIdeje = new DateTime(1997, 6, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Szerzo = "J.K. Rowling"
                        },
                        new
                        {
                            Id = 3,
                            Cim = "A kis herceg",
                            Isbn = "978-0-15-601219-5",
                            Kategoria = "Mese",
                            KiadasIdeje = new DateTime(1943, 4, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Szerzo = "Antoine de Saint-Exupéry"
                        },
                        new
                        {
                            Id = 4,
                            Cim = "1984",
                            Isbn = "978-0-452-28423-4",
                            Kategoria = "Disztópia",
                            KiadasIdeje = new DateTime(1949, 6, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Szerzo = "George Orwell"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
